### ISSUE TITLE
[Bug] - Envmon MIB should not reference entitymib in tags in cisco-all-devices.yml

### ISSUE THREAD

**Issue by araddas** [kentik/snmp-profiles#125]
Currently the CISCO-ENVMON-MIB in cisco-all-devices.yml is tagging entity_index, entity_description, entity_class, entity_name, entity_serial, entity_model using the index from the CISCO-ENVMON-MIB, this not valid and should be removed from this profile.

**snmp walk of ciscoEnvMonSupplyStatusDescr and entPhysicalDescr**
![envmon_entity_description_incorrect](https://user-images.githubusercontent.com/24640633/148590281-2a8fe5cc-a32d-4df0-8e1d-d5421f2790de.png)

**NewRelic UI**
<img width="1158" alt="Screen Shot 2022-01-07 at 10 32 41 AM" src="https://user-images.githubusercontent.com/24640633/148590964-ee2e570b-7958-4075-b8ee-a18eac6e16a8.png">

**Comment by Mesverrum** [comment]
This is going to take a bit to clear up, it looks like Cisco must have changed the way this treat this OID at some point because I have about a dozen walks in my collection that show correct mapping of all the ciscoEnvMonMIB indexes to the entPhysicalTable indexes, but now that I'm digging through them I also have some where they behave the way your device is showing. So far it seems to be inconsistent across a wide range of firmware versions and models.  I have walks from catalysts, ios routers, and nx-os devices that all exhibit both patterns. 

example from a 3750 stack where the indexes match up correctly
entity_description
.1.3.6.1.2.1.47.1.1.1.1.2.1003 = String: "Switch 1 - WS-C3750G-48TS - Power Supply 0"
.1.3.6.1.2.1.47.1.1.1.1.2.2003 = String: "Switch 2 - WS-C3750G-48TS - Power Supply 0"
entity_name
.1.3.6.1.2.1.47.1.1.1.1.7.1003 = String: "Switch 1 - WS-C3750G-48TS - Power Supply 0"
.1.3.6.1.2.1.47.1.1.1.1.7.2003 = String: "Switch 2 - WS-C3750G-48TS - Power Supply 0"
power_status_description (the same oid you show in your walk snippet)
.1.3.6.1.4.1.9.9.13.1.5.1.2.1003 = String: "Sw1, PS1 Normal, RPS NotExist"
.1.3.6.1.4.1.9.9.13.1.5.1.2.2003 = String: "Sw2, PS1 Normal, RPS NotExist"

As an interim work around while we try to figure out how to identify which cisco gear does and does not use the entity indexes you could facet on power_status_description instead, but I wouldn't be surprised if you also have both kinds of devices in your environment.

**Comment by i3149** [comment]
Talked with @cmcgrath138 , we decided that the best bet is to probably just facet on `power_status_description`.

**Comment by Mesverrum** [comment]
Looks like there isn't a clear solution we can implement on our end that covers both scenarios, so the workaround is just to have users use power_status_description or entity_description as necessary for their devices.
