### ISSUE TITLE
[Missing SNMP Profile]-Broadforward-BFX-DRA

### ISSUE THREAD

**Issue by Gopinathind** [kentik/snmp-profiles#138]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Broadforward

Device Model: BFX-DRA

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.39216.

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations): Basically the counters and the Status.

       ( dmtrPeerAdminStatus, dmtrPeerDiameterId, dmtrPeerConnectionStatus,
        dmtrPeerTransportStatus, 
       dmtrPeerRealm, 
         dmtrPeerProductName,
        dmtrPeerRxCount, dmtrPeerTxCount,
        dmtrPeerLastOOS, dmtrPeerOOSDuration, dmtrPeerOOSCount,
        dmtrPeerTransLastOOS, dmtrPeerTransOOSDuration, dmtrPeerTransOOSCount,
        dmtrPeerSendQueueSize, dmtrPeerSendQueueSizeMax,
        dmtrPeerTxFailedCount, dmtrPeerTimeoutCount,
       dmtrPeerRxResult2xxxCount,
      dmtrPeerRxResult4xxxCount,
        dmtrPeerRxResult5xxxCount, 
        dmtrPeerRxBytesCount, dmtrPeerTxBytesCount,
dmtrPeerSctpRxSacks, dmtrPeerSctpTxSacks,
    dmtrPeerSctpRxDups, dmtrPeerSctpRxGapAcks,dmtrSctpAddrState)
and some more. 

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/Gopinathind/a56c5492f5dcc5a534d6aa638e8a9938

---
Example SNMP walk commands: added them in the above gist link
```
snmpwalk added to the Gist Link above

**Comment by thezackm** [comment]
thanks for the request @Gopinathind; can you please update your gist to include an SNMP walk formatted as requested in the issue template? the command you used is missing the formatting flags: 

```
snmpwalk -v 2c -On -c $COMMUNITY $IP_ADDRESS . >> snmpwalk.out
```

Specifically, the `-On` flags provide a numerical OID output that makes parsing the results exponentially easier for us. 

e.g.; right now your results look like this:

```
SNMPv2-MIB::sysObjectID.0 = OID: NET-SNMP-MIB::netSnmpAgentOIDs.10
```

we need them to look like this:
```
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.8072.3.2.10
```

**Comment by Gopinathind** [comment]
Hey @thezackm thank for your quick comment, I have added the snmpwalk.out in the gist with the OID as requested.

**Comment by Gopinathind** [comment]
Hi guys, when can I expect this to be updated?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mesverrum** [comment]
@Gopinathind 
Given that this is a pretty uncommon piece of kit it's going to take a bit to get this profile figured out and processed, I'd expect it's about a week out with various obligations Zack and I have in the pipe right now.

A question for you, what do you call this thing so I know what kind of name to given the profile?

**Comment by Gopinathind** [comment]
Hi @Mesverrum , Thanks for turning out with a time, the profile is for DRA- "Diameter Routing Agent"

**Comment by Mesverrum** [comment]
#157 should get you going.

There are some extra steps you'll have to do for this.  
A new container image should be ready shortly with this profile built into it so pull that image down.  

You should already have your snmp-base.yaml file with the list of all your devices, because this device just came back as a generic Linux host there wasn't anything to key in on to automatically associate this profile to your devices.  So you will need to edit the devices section of your snmp-base.yaml file and for each of these you would need to edit the line where it says 
`mib_profile: net-snmp.yml`
to 
`mib_profile: "!diameter.yml"`
This forces it to ignore the build in matching and just use the profile you specify.  This step should be repeated for each DRA device.

Then search for `mibs_enabled` under the global section and you need to add this to the list
`- MF-DIAMETER-MIB`

At that point you can remove your container, fire up a new one and you *should* start getting this data back.  Let us know if you run into any issues.

**Comment by Gopinathind** [comment]
Thanks a lot @Mesverrum , 
Let me do the steps which you have advice and feedback here.
