### ISSUE TITLE
Missing SNMP Polling Profile for IBM Datapower Gateway

### ISSUE THREAD

**Issue by kolpriya90** [kentik/snmp-profiles#232]
Device Vendor: IBM Datapower Gateway

Device Model:  SNMPv2-SMI::enterprises.14685.1.8

System Object Identifier (SysOID): SNMPv2-SMI::enterprises.14685.1.8

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - CPU
 - Memory
 - Disk

Gist Link:

**Comment by thezackm** [comment]
@kolpriya90 - please run the walk again with the formatting flags on the command as requested in the issue template; the output of the walk should be numeric.

i.e.;

Instead of this: `SNMPv2-MIB::sysDescr.0 = STRING: IBM DataPower Gateway`

We need this format: `.1.3.6.1.2.1.1.1.0 = STRING: IBM DataPower Gateway`

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by kolpriya90** [comment]
@thezackm I've uploaded a new file with snmpwalk output. 
https://gist.github.com/kolpriya90/8bfee4fb2f610e0344d82363a2b6212d
