### ISSUE TITLE
[Missing SNMP Polling Profile] Cisco Aironet 3800 Series WLC

### ISSUE THREAD

**Issue by travisroberts-sf** [kentik/snmp-profiles#333]
Device Vendor: Cisco

Device Model: AIR-CT3504-K9

System Object Identifier (SysOID): .1.3.6.1.4.1.9.1.2427

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):
- Uptime
- Interface metrics/status
- AP metrics/status
- Model Number
- Serial Number

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: https://gist.github.com/travisroberts-sf/f0ae822b3e1977201718d621f602cb84
FYI.... the out file for this snmp walk was huge so there is a lot in this gist.

**Comment by thezackm** [comment]
@travisroberts-sf - this device looks to fall under the current [cisco-wlc.yml](https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/cisco/cisco-wlc.yml) profile, with the caveat that it doesn't seem to have support for CPU or Memory utilization metrics based on the results of the SNMP walk. 

If you have any way to identify the right OIDs to collect these metrics for this particular model, please let us know. Otherwise we will close this out after adding the sysObjectID to match on the existing profile for your discovery needs.

You can see below a breakdown of the vendor-specific MIBs found in the walk output, the vast majority are more about inventory and configuration than status and performance.

---

| Root OID                | MIB                                                                          |
|-------------------------|------------------------------------------------------------------------------|
| 1.3.6.1.4.1.9.9.13.*    | [ciscoEnvMonMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.13)                 |
| 1.3.6.1.4.1.9.9.23.*    | [ciscoCdpMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.23)                    |
| 1.3.6.1.4.1.9.9.176.*   | [ciscoRFMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.176)                    |
| 1.3.6.1.4.1.9.9.512.*   | [ciscoLwappWlanMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.512)             |
| 1.3.6.1.4.1.9.9.513.*   | [ciscoLwappApMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.513)               |
| 1.3.6.1.4.1.9.9.515.*   | [ciscoLwappWebAuthMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.515)          |
| 1.3.6.1.4.1.9.9.517.*   | [ciscoLwappReapMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.517)             |
| 1.3.6.1.4.1.9.9.518.*   | [ciscoLwappMfpMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.518)              |
| 1.3.6.1.4.1.9.9.520.*   | [ciscoLwappCcxRmMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.520)            |
| 1.3.6.1.4.1.9.9.521.*   | [ciscoLwappWlanSecurityMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.521)     |
| 1.3.6.1.4.1.9.9.522.*   | [ciscoLwappDot11ClientCalibMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.522) |
| 1.3.6.1.4.1.9.9.523.*   | [ciscoLwappClRoamMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.523)           |
| 1.3.6.1.4.1.9.9.524.*   | [ciscoLwappQosMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.524)              |
| 1.3.6.1.4.1.9.9.525.*   | [ciscoLwappTsmMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.525)              |
| 1.3.6.1.4.1.9.9.543.*   | [ciscoLicenseMgmtMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.543)           |
| 1.3.6.1.4.1.9.9.576.*   | [ciscoLwappMobilityMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.576)         |
| 1.3.6.1.4.1.9.9.577.*   | [ciscoLwappAclMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.577)              |
| 1.3.6.1.4.1.9.9.598.*   | [ciscoLwappAAAMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.598)              |
| 1.3.6.1.4.1.9.9.599.*   | [ciscoLwappDot11ClientMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.599)      |
| 1.3.6.1.4.1.9.9.606.*   | [ciscoLwappMeshLinkTestMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.606)     |
| 1.3.6.1.4.1.9.9.610.*   | [ciscoLwappRogueMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.610)            |
| 1.3.6.1.4.1.9.9.612.*   | [ciscoLwappDot11MIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.612)            |
| 1.3.6.1.4.1.9.9.614.*   | [ciscoLwappDot11LdapMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.614)        |
| 1.3.6.1.4.1.9.9.615.*   | [ciscoLwappRrmMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.615)              |
| 1.3.6.1.4.1.9.9.616.*   | [ciscoLwappMeshMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.616)             |
| 1.3.6.1.4.1.9.9.617.*   | [ciscoLwappMeshStatsMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.617)        |
| 1.3.6.1.4.1.9.9.618.*   | [ciscoLwappSysMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.618)              |
| 1.3.6.1.4.1.9.9.619.*   | [ciscoLwappLocalAuthMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.619)        |
| 1.3.6.1.4.1.9.9.620.*   | [ciscoLwappMeshBatteryMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.620)      |
| 1.3.6.1.4.1.9.9.622.*   | [ciscoLwappDot11ClientTsMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.622)    |
| 1.3.6.1.4.1.9.9.623.*   | [ciscoLwappCdpMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.623)              |
| 1.3.6.1.4.1.9.9.686.*   | [ciscoLwappInterfaceMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.686)        |
| 1.3.6.1.4.1.9.9.720.*   | [ciscoTrustSecSxpMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.720)           |
| 1.3.6.1.4.1.9.9.778.*   | [ciscoLwappRFMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.778)               |
| 1.3.6.1.4.1.9.9.792.*   | [ciscoLwappDhcpMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.792)             |
| 1.3.6.1.4.1.9.9.836.*   | !! UNKNOWN !!                                                                    |
| 1.3.6.1.4.1.9.9.837.*   | [ciscoLwappOpendnsMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.837)          |
| 1.3.6.1.4.1.9.9.838.*   | [ciscoLwappCloudServicesMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.838)    |
| 1.3.6.1.4.1.9.9.840.*   | [ciscoLwappNetflowMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.840)          |
| 1.3.6.1.4.1.9.9.841.*   | [ciscoLwappNbarMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.841)             |
| 1.3.6.1.4.1.9.9.843.*   | [ciscoLwappHaMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.843)               |
| 1.3.6.1.4.1.9.9.845.*   | [ciscoLwappPmipMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.845)             |
| 1.3.6.1.4.1.9.9.846.*   | [ciscoLwappMobilityExtMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.846)      |
| 1.3.6.1.4.1.9.9.847.*   | [ciscoLwappIpv6MIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.847)             |
| 1.3.6.1.4.1.9.9.848.*   | [ciscoLwappTunnelMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.848)           |
| 1.3.6.1.4.1.9.9.852.*   | [ciscoLwappU3InterfaceMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.852)      |
| 1.3.6.1.4.1.9.9.855.*   | [ciscoVimMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.855)                   |
| 1.3.6.1.4.1.9.9.9998.*  | [ciscoLwappExtMIB](http://oid-info.com/get/1.3.6.1.4.1.9.9.9998)             |
| 1.3.6.1.4.1.9.9.99991.* | !! UNKNOWN !!                                                                    |

**Comment by travisroberts-sf** [comment]
Thank you.  One question however, is why these devices aren't getting
identified correctly in New Relic.  They are still showing up under Kentik
Defaults.

*TRAVIS ROBERTS *

Sr. Site Reliability Engineer | Salesforce

Mobile: 253-290-8477


<https://smart.salesforce.com/sig/travis.roberts//us_mb/default/link.html>

**Comment by thezackm** [comment]
@travisroberts-sf - you need to run a fresh discovery with the `replace_devices` attribute set to `true` in order for the config file to update. If that's not an easy option, you can manually update the devices with the following settings in the `devices` block:

```yaml
devices:
  deviceOne_10.10.10.1:
    device_name: deviceOne
    ...
    provider: kentik-wireless-controller
    mib_profile: cisco-wlc.yml
```

and then make sure the appropriate MIBs are in the `global` block:

```yaml
global:
  ...
  mibs_enabled:
  - CISCO-RF-MIB
  - CISCO-VPC-MIB
  - HOST-RESOURCES-MIB
  - IF-MIB
```

This will setup your telemetry to build [Wireless Controller](https://github.com/newrelic/entity-definitions/blob/main/definitions/ext-wireless_controller/definition.yml) entities in our UI. Note that the current dashboard was created from telemetry on an Aruba WLC, so changes will most likely be needed to get your UI more customized for these devices. Please have yourself or @araddas ping us in Slack when you've got the config files working and we'll start that process with you directly.
