### ISSUE TITLE
Cisco FMC is discovering as Kentik Default

### ISSUE THREAD

**Issue by bradleyk1968** [kentik/snmp-profiles#388]
Device is discovering as Kentik Default.

Device Vendor: Cisco Firewall Management Center
Device Model: FMC

See attached SNMP-WALK.

[Discovered Kentik Default for Cisco FMC.log](https://github.com/kentik/snmp-profiles/files/9253150/Discovered.Kentik.Default.for.Cisco.FMC.log)

**Comment by Mesverrum** [comment]
@bradleyk1968 Any chance you could rerun those snmp walks using the syntax from our issues example, for us to do profiles we need the number OID's, not the string versions

snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out
The -On flag specifies the output format as numbers

we're looking for output like:
`1.3.6.1.2.1.2.2.1.18 = Counter32: 0`

instead of 
`IF-MIB::ifOutNUcastPkts.2 = Counter32: 0`


Thanks

**Comment by bradleyk1968** [comment]
Yes, here you go.
[SNMP-WALK.log](https://github.com/kentik/snmp-profiles/files/9253321/SNMP-WALK.log)

**Comment by Mesverrum** [comment]
So based on the data in the walk this is essentially a Linux appliance, and Cisco hasn't actually added any custom OID's beyond what generic Linux servers already contain. See these two key fields we look at to identify what something is.

.1.3.6.1.2.1.1.1.0 = STRING: Linux las-fmc01.ghs.cdk.com 4.14.131sf.westmere-secure-2 #1 SMP Fri Sep 6 19:34:04 UTC 2019 x86_64
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.8072.3.2.10

At this point we do bundle Kentik Defaults with Linux servers because they don't have any differences in the profile but we might look at breaking them out to be a separate entity.  Its not going to specifically say FMC, its likely to be a more generic category like 'net-snmp device' which is probably pretty similar to how they show up in your old SW environment as well if we were to compare.  There is a code freeze on changes to the UI at NR this week during the recharge so I expect you won't see the adjustments on your end until maybe the 22nd.  I'll leave this open until those changes go through.

**Comment by bradleyk1968** [comment]
Okay, let me know and thanks.

**Comment by bradleyk1968** [comment]
Any additional feedback on this?  Having the device go into 'net-snmp-linux'  would be fine if doable.  Let me know and thanks.

**Comment by bradleyk1968** [comment]
Any additional feedback on this? Having the device go into 'net-snmp-linux' would be fine if doable. Let me know and thanks.

**Comment by bradleyk1968** [comment]
@Mesverrum

**Comment by Mesverrum** [comment]
This one is in the back log, its just been getting stalled on other priorities.

**Comment by Mesverrum** [comment]
@bradleyk1968  FYI i submitted this request to the team who owns that, should manifest in your UI within 5-10 days

**Comment by bradleyk1968** [comment]
Status for this?

**Comment by Mesverrum** [comment]
Just confirmed this has gone into prod and can see it in your account, currently net-snmp and wan optimizer devices show up under other devices instead of the network category but that's getting updated as well soon.

**Comment by bradleyk1968** [comment]
Thanks… will check this tomorrow.KevinSent from my iPhoneOn Nov 21, 2022, at 5:24 PM, Marc Netterfield ***@***.***> wrote:﻿
Just confirmed this has gone into prod and can see it in your account, currently net-snmp and wan optimizer devices show up under other devices instead of the network category but that's getting updated as well soon.
