### ISSUE TITLE
[Missing SNMP Polling Profile] NetApp H615C

### ISSUE THREAD

**Issue by BharathCtx** [kentik/snmp-profiles#439]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: NetApp

Device Model: H615C

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID): .1.3.6.1.4.1.8072.3.2.10

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - All the essential metrics which will come for Netapp
 - RACK-MIB 
 - All agentInfo like (QunataStatusProbe,agentBMCVersion,agentBMCGuid,agentServerIdentify,agentChassisStatus,agentPowerControl,agentSystemMA,agentBMCIP,agentBMCMAC,agentBMCIPSource)
 - All SystemStatus like (voltageStatusOverall,voltageStatusList,fanStatusOverall,temperatureStatusOverall,temperatureStatusList, fanStatusList,powerSupplyRedundancyetc.,)
 - All DeviceInfo like (ProcessorDeviceStatus, ProcessorDeviceInfoTableEntry, processorDeviceInfoLocationName, etc.,)
 - All Memory Device Table like (MemoryDeviceStatus, MemoryDeviceInfoTableEntry, etc.,)
 - All Fan Device Table like (FanDeviceInfoTableEntry, fanDeviceInfoTable, etc.,)
 - All Temperature Device Table like - TemperatureDeviceInfoTableEntry
 - All Voltage Device Table - VoltageDeviceInfoTableEntry
 - All FRU Device Table - FRUDeviceInfoTableEntry
 - All SEL Device
 -
 
If there is a New Relic technical support case related to this request, please provide the case number: #00063097

**Please provide a [public gist](https://gist.github.com/) with a sanitized** *(sensitive information removed)* **SNMP walk of the device. Providing MIB files is not a substitute for an SNMP walk and failure to provide one here will result in delays for closing this issue. The output of these commands shows the "true story" of what a device will respond to in SNMP and is used to ensure that our profiles are efficient and accurate for your devices.**

Gist Link: snmpwalk uploaded to case 00063097

---
Example SNMP walk commands:
```
# v2c example
snmpwalk -v 2c -t 10 -On -c $COMMUNITY_STRING $IP_ADDRESS . >> snmp_walk.out

# v3 example
snmpwalk -v3 -t 10 -l authPriv -u $USERNAME -a MD5|SHA -A $AUTH_PASS -x DES|AES -X $PRIV_PASS -ObentU -Cc $IP_ADDRESS . >> snmp_walk.out
```

**Comment by Mesverrum** [comment]
@BharathCtx 
The walk you provided in the case does not have any of the OID's shown in your MIB documentation.  It's possible your walk timed out or was otherwise interrupted, or that you might have been trying to connect to the wrong interface on the appliance.  

Further, the sysOID your devices present is the generic one for all net-snmp *nix servers, so the automatic discovery is always going to just assign a generic Linux profile.  For cases like that you would need to manually set the mib_profile attribute on your config file.  Right now it probably has something like

mib_profile: base
provider: Kentik-Default

and you'd need to edit the file like so to force it to use the Netapp profile instead of the automatic one.

mib_profile: "!netapp-hci"
provider: kentik-netapp-hci

Make sure you use the double quotes and ! to get the profile syntax correct.
