### ISSUE TITLE
[Missing SNMP Polling Profile] checkpoint watchguard

### ISSUE THREAD

**Issue by wuetz** [kentik/snmp-profiles#446]
[NOTE]: # ( ^^ Please add the Device Vendor and Model in the title above. ^^ )

Device Vendor: Checkpoint

Device Model: Watchguard T40

[NOTE]: # (If you do not know your SysOID, it can be gathered from the SNMP walk you provide at the end of this issue. It is the value of this OID in the SYSTEM-MIB: `1.3.6.1.2.1.1.2.0`)

System Object Identifier (SysOID):  `iso.3.6.1.4.1.3097.1.5.87`

**Comment by Mesverrum** [comment]
@wuetz You did not include a sanitized SNMP walk from your device so we cannot build a profile.  Please attach what we need to proceed.

I double checked to make sure and watchguard product line is separate from the checkpoint firewall profile we already have so it does not appear that we could just add this model to that existing profile, we'll need to build something totally new for these.

**Comment by wuetz** [comment]
@Mesverrum do you have an estimated timeline, when we have this in place?

**Comment by Mesverrum** [comment]
@wuetz That walk does not contain anything that is not already covered by the default base profile.  We can make a change to get this labeled as something different, but that's just going to be a UX change and won't actually add any Watchguard specific data because as far as what is in SNMP the firebox line appears to a dressed up Linux server.

**Comment by wuetz** [comment]
@Mesverrum okay, then please do the labeling.
