### ISSUE TITLE
[Missing SNMP Polling Profile] VMware ESXi 6.7.0

### ISSUE THREAD

**Issue by jlrgraham23** [kentik/snmp-profiles#477]
Device Vendor: VMWare

Device Model: ESXi 6.7.0

System Object Identifier (SysOID): `.1.3.6.1.4.1.6876.4.1`

List of critical metrics that you expect in the profile (does not need to be all-inclusive, just a general idea of your expectations):

 - Device shows in New Relic as using a generic profile.
 
If there is a New Relic technical support case related to this request, please provide the case number: 00075880

**Comment by Mesverrum** [comment]
@jlrgraham23 You did not attach an SNMP walk to this issue or send one as part of the GTS case.  Without those walks we cannot build a profile.

Further, as a general rule with New Relic you would want to use the vSphere integration to monitor ESXi hosts instead of SNMP.  https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration/

If you can attach a gist of a walk we can get started on building a profile.

**Comment by jlrgraham23** [comment]
Hi @Mesverrum, the file was uploaded as `snmpwalk-vmware-esxi-6.7.out`.  If I need to re-upload these can you have our support engineer provide an upload link again to make sure we're all on the same page?

**Comment by ASchneider-GitHub** [comment]
Please note that `snmpwalk` output files have been transferred from ShareFile to Case #00075880.

**Comment by jlrgraham23** [comment]
Thanks @ASchneider-GitHub !
