### ISSUE TITLE
SNMP roomalert3e.yml help

### ISSUE THREAD

**Issue by EddGH1337** [kentik/snmp-profiles#512]
Hello, we would like to request your help to create a config file snmp-base.yml for a SNMP version roomalert3e.
At this moment we have the snmp-base.yml file for version roomalert3s.

We are attaching the file ROOMALERT3E.MIB for further details.
Kind regards.
[RA3E-MIB.zip](https://github.com/kentik/snmp-profiles/files/10440579/RA3E-MIB.zip)

**Comment by Mesverrum** [comment]
Hi @EddGH1337, this isn't really the forum for that, it would be a support case with New Relic tech support.  Regardless I can tell you that a mib file will not be relevant for this, since there is already a profile for the room alert device all you need to do is stand up a fresh container with a snmp-base file as per the New Relic guided install prompts.  Assuming that your community string is correct then the discovery will just auto populate everything for the devices section and automatically map each device to the correct profile.
