### ISSUE TITLE
[Update Exisiting profile with More OIDs] IBM-WGA

### ISSUE THREAD

**Issue by Nithishduda10** [kentik/snmp-profiles#534]
- Provider: kentik-ibm-wga
- Sysobjectid: 1.3.6.1.4.1.8072.3.2.10.ibm-wga

The OIDs we're looking for to report to Newrelic UI were missed by the existing profile we had for ibm-wga. Case #00086472 has been opened with Newrelic. So here I am with OIDs after Newrelic suggested we open a case with Kentik GitHub.

Could you please add following OIDs to ibm-wga Profile:

percentage of user CPU time: 1.3.6.1.4.1.2021.11.9.0
percentages of system CPU time: 1.3.6.1.4.1.2021.11.10.0
percentages of idle CPU time: 1.3.6.1.4.1.2021.11.11.0

**Comment by Nithishduda10** [comment]
Hi Team, 

Any update on this?
Also it doesn't gave me an option to add Label for this issue. 
Requesting for help to get this done ASAP!

Thanks

**Comment by Mesverrum** [comment]
@Nithishduda10 This repo is essentially a volunteer effort for the maintainers, as they have time in between other obligations.  If you want to have a change happen more quickly then you are free to edit the profile and suggest a PR yourself based on the existing examples and _template file. Otherwise we triage these as we are able to make time.

**Comment by Mesverrum** [comment]
@Nithishduda10 As a heads up, I added in the OIDs you asked for, but they are marked as deprecated so I also added in their new versions. https://www.circitor.fr/Mibs/Html/U/UCD-SNMP-MIB.php#ssCpuUser

**Comment by Nithishduda10** [comment]
Cool, I didn't realise that those OIDs are deprecated. Thanks for Adding Newer OIDs @Mesverrum
