### ISSUE TITLE
SNMP roomalert3e test failed

### ISSUE THREAD

**Issue by EddGH1337** [kentik/snmp-profiles#542]
Hi,

As result of tests we still having difficulties with SNMP configuration. 
Previously we submit a new issue requesting your help to get a config file for a roomalert3e. After you provide us the file we perform some tests with the new relic integration.
As you can see in the attached images, we still having issues with the SNMP.

1) We notice that when profiles are charged from the Docker image the Avetech profiles did not load properly, this can be see in the imaged named "profile_load_errors.png"

2)Also, the main error message we get is the following which is showed in the image named error_message.png :
- There was an SNMP polling error with the CustomDeviceMetrics walking OID 1.3.6.1.2.1.1.3.0 after 0 retries: error reading from socket read up 192.168.65.3:58055-> 198.18.206.240.161: recvfrom: connection refused.

We would like to know why is this problema persisting.
Kind regards
[SNMP_Errors.zip](https://github.com/kentik/snmp-profiles/files/10582568/SNMP_Errors.zip)

**Comment by EddGH1337** [comment]
it's been a while without any updates from you.

We would like to know if there has been any advances with the troubleshoot of the reported issue?
If you need more information for further investigation please let us know.
Thanks in advance for your time.

Kind Regards.

**Comment by EddGH1337** [comment]
Hi team, we still having some issues with the SNMP in the attached folder you can find the logs we receive in our lasts tests, also we are attaching SNMP-base file that we are using in order to provide more information that could lead us to a possible solution of the reported issue.

[snmp_evidence.zip](https://github.com/kentik/snmp-profiles/files/10807339/snmp_evidence.zip)

**Comment by Mesverrum** [comment]
@EddGH1337 This is not really the place to do troubleshooting and debugging, you'll be better served by opening a support ticket with New Relic.

Looking at your logs there was no error with loading the roomalert profiles, I also notice you've set your system to `use_snmp_v1: true` which is pretty rare these days, maybe your device requires it, i don't know, but I generally encounter with v2c or v3 so that seems out of place.
Getting further in I see that initially your device rejected the attempt to poll the sysUptime, which is one of the basic checks ktranslate uses to validate that SNMP communication is working and is used for a bunch of math operations.  Then on the second try it was able to connect successfully.  Nothing in these logs indicates any problem with the profile so this isn't the place to troubleshoot SNMP issues on your environment.

...
2023-02-22T17:33:05.251 ktranslate/snmp [Info] KTranslate Recursing into /etc/ktranslate/profiles/kentik_snmp/avtech
...
2023-02-22T17:33:05.331 ktranslate/snmp [Info] KTranslate>testing1  Running with SNMP v1
...
2023-02-22T18:10:13.742 ktranslate/snmp [Warn] KTranslate>testing1 There was an SNMP polling error with the CustomDeviceMetrics walking OID 1.3.6.1.2.1.1.3.0 after 0 retries: error reading from socket: read udp 192.168.65.3:59747->198.18.206.240:161: recvfrom: connection refused.
2023-02-22T18:10:24.115 ktranslate/snmp [Info] KTranslate>testing1 CustomDeviceMetrics SNMP retry 1 on OID 1.3.6.1.2.1.1.3.0 succeeded
