### ISSUE TITLE
HP LaserJet Printers

### ISSUE THREAD

**Issue by cyclone21** [kentik/snmp-profiles#764]
Using NewRelic and ktranslate, my printers are being detected as Kentic Defaults.
i.e. HP LaserJet Pro MFP M521dn and HP LaserJet MFP M227fdw

Since they have a tendency to go randomly offline I would like to be able to monitor them

**Comment by thezackm** [comment]
@cyclone21 - thanks for your submission; [as noted in the repo](https://github.com/kentik/snmp-profiles?tab=readme-ov-file#note-this-repo-is-no-longer-actively-creating-new-profiles-based-on-requests-in-issues-we-will-accept-pull-requests-from-the-community-for-new-profiles-but-cannot-create-any-more-ourselves), we are not creating new profiles in this repo, but are happy to accept guest pull requests to add new functionality.

since you've mentioned New Relic, you can use [this documentation](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/snmp-profiles/) to guide you with your request.
